### ISSUE TITLE
Input resolutions other than 432x240

### ISSUE THREAD

**Issue by CosmosXIII** [ruiliu-ai/DSTT#4]
I am trying to test your work with input images of resolution 640x448 but I keep getting the following error:

 File "/home/cosmos/AI/DSTT/model/DSTT.py", line 241, in forward
    key = key.view(b, t, 2, self.h//2, 2, self.w//2, self.head, c_h)
RuntimeError: shape '[1, 11, 2, 10, 2, 18, 4, 128]' is invalid for input of size 11556864

Is it only possible to use 432x240 input images with the pre-trained model?
If so, would I need to train a new model specifically for the 640x448 resolution?
I also tried to change the resolution in youtube-vos.json and run the train.py script but I get a similar error there.

Can you explain how to make it work for resolutions other than 432x240?

Thank you!

**Comment by ruiliu-ai** [comment]
You can set the input resolution to be multiple of 12, otherwise it will be a little difficult to match the resolution. Also remember to modify https://github.com/ruiliu-ai/DSTT/blob/master/model/DSTT.py#L106 to be proper size.

**Comment by CosmosXIII** [comment]
Thank you for your reply.

I set the resolution to multiple of 12, in my case 648x456, and changed the output_size to (114, 162) which I guessed to be the input height and width divided by 4, is this correct?

Executing test.py with the changes above seems to progress further than before but now I am getting the following error:
```
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [5549,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
...
 /pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [5555,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "test.py", line 163, in <module>
    main_worker()
  File "test.py", line 137, in main_worker
    pred_img = pred_img.cpu().permute(0, 2, 3, 1).numpy()*255
RuntimeError: CUDA error: device-side assert triggered
```
Do you know what is the problem here and how to fix it?

Thank you again.

**Comment by ruiliu-ai** [comment]
Sorry, did not meet this. Maybe the issue of Pytorch version? I used Pytorch 1.1.0.

**Comment by CosmosXIII** [comment]
Thank you for your reply.

Unfortunately, I tried with Pytorch 1.1.0 and Cuda 10.0 still getting the same error.

**Comment by JasonZK** [comment]
I‘ve met the same problem, and my case is 1024*576.
Please let me know if you solved this problem.
Thank you very much!

**Comment by napohou** [comment]
any update?

**Comment by tawsinDOTuddin** [comment]
The code seems to be only work on a specific input resolution which the model trained on. If I want to test it with dimension other than 432x240, I can but I have to train the model with that specific dimension. right?
